export const SET_COMPANIES_NAME = "SET_COMPANIES_NAME";
export const SET_COMPANIES_LOGO = "SET_COMPANIES_LOGO";

export const ERR_COMPANIES_NAME = "SET_COMPANIES_NAME";
export const ERR_COMPANIES_LOGO = "SET_COMPANIES_LOGO";

export const SET_COMPANIES_THEME_COLOUR = "SET_COMPANIES_THEME_COLOUR";

export const ADD_COMPANIES_STAFF_MEMBER = "ADD_COMPANIES_STAFF_MEMBER";
export const SET_COMPANIES_STAFF_MEMBER = "SET_COMPANIES_STAFF_MEMBER";
export const DEL_COMPANIES_STAFF_MEMBER = "DEL_COMPANIES_STAFF_MEMBER";
export const ERR_COMPANIES_STAFF_MEMBER = "ERR_COMPANIES_STAFF_MEMBER";
