export const SET_THEME_LOGO = "SET_THEME_LOGO";
export const SET_THEME_COLORS = "SET_THEME_COLOURS";
export const RESTORE_MAIN_THEME = "CHANGE_MAIN_THEME";

export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

export const AUTHENTICATION_REMEMBER = "AUTHENTICATION_REMEMBER";
